services:
  - type: web
    name: pierre-trends-backend  
    env: python
    plan: free
    pythonVersion: "3.9"  # Match your local version
    buildCommand: pip install -r requirements.txt
    startCommand: cd trends && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: pierre-trends-backend
          property: port
      - key: NEWS_API_KEY
        sync: false
